apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    component: node-exporter
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  clusterIP: None
